name: CI

on:
  push:
    tags:
    - '*.*.*'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env:
        DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
    - name: Push package to NuGet
      run: dotnet nuget push **/*.nupkg 
               --api-key ${{ secrets.NUGET_TOKEN }}
               --source https://api.nuget.org/v3/index.json
