name: Release

on:
  push:
    tags:
    - '*.*.*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env:
        DISCOGS_TOKEN: ${{ secrets.DISCOGS_TOKEN }}
        DISCOGS_USERNAME: ${{ secrets.DISCOGS_USERNAME }}
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}    
    - name: NuGet push
      run: dotnet nuget push **/*.nupkg 
               --api-key ${{steps.login.outputs.NUGET_API_KEY}}
               --source https://api.nuget.org/v3/index.json
